### ISSUE TITLE
For plotting counts, use geom_line rather than geom_smooth

### ISSUE THREAD

**Issue by dicook** [gavinchin/honours2017#2]
geom_smooth makes it look prettier but introduces error, e.g. negative counts.

**Comment by dicook** [comment]
it is ok for fig 2, but for fig 6 it looks weird with the negative counts. i can see why you have used smooth, and its a very efficient idea, to make a quick average of multiple values.

**Comment by gavinchin** [comment]
changed to geom_path, as it seemed appropriate for fig 6 and seems to work quite well.
